spring:
    thymeleaf:
      prefix: classpath:/views/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      cache: false
    jpa:
      show-sql: true
    devtools:
      add-properties: true
    profiles:
      active: dev
mybatis:
  mapper-locations: classpath:mapper/*.xml